---
- name: Ensure AlmaLinux GPG key is installed
  get_url:
    url: https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux
    mode: '0644'

- name: Remove conflicting AlmaLinux .repo files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/yum.repos.d/almalinux.repo
    - /etc/yum.repos.d/AlmaLinux-BaseOS.repo
    - /etc/yum.repos.d/AlmaLinux-AppStream.repo
  ignore_errors: yes

- name: Configure custom AlmaLinux repositories using BMCC mirror
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.desc }}"
    baseurl: "{{ item.url }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux
  loop:
    - { name: 'baseos', desc: 'AlmaLinux $releasever - BaseOS (BMCC Mirror)', url: 'https://mirrors.bmcc.edu/alma/$releasever/BaseOS/$basearch/os/' }
    - { name: 'appstream', desc: 'AlmaLinux $releasever - AppStream (BMCC Mirror)', url: 'https://mirrors.bmcc.edu/alma/$releasever/AppStream/$basearch/os/' }

- name: Clean DNF metadata
  command: dnf clean all
  changed_when: false

- name: Rebuild DNF cache
  command: dnf makecache
  changed_when: false

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    
- name: Install Automatic DNF Updater
  dnf:
    name: dnf-automatic
    state: latest

- name: Apply Updates Automatically
  ansible.builtin.lineinfile:
    path: /etc/dnf/automatic.conf 
    regexp: '^apply_updates'
    line: apply_updates = yes

- name: Enable and Start DNF-Automatic
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    enabled: true
    state: restarted